export const slides = [
    {
        alt: 'A crawler crane winching a crate out of the water',
        body: 'Notta Boss is an Auckland studio run by <mark>one senior engineer</mark>. Twenty years of shipping products and pulling <mark>legacy systems</mark> out of the swamp, now building websites and SaaS you can actually look at.',
        cta: 'See the work',
        figure: 'dredge',
        label: 'Notta Boss',
        title: 'Built to last',
        to: '/work',
    },
    {
        alt: 'An app window coming apart in layers',
        body: 'Marketing sites, booking flows, portals. We work with <mark>Laravel, Livewire, Vue</mark> and <mark>Tailwind</mark>, and build things that are fast, easy to edit, and still standing in five years.',
        cta: 'See the work',
        figure: 'exploded',
        label: 'Expertise',
        title: 'Websites',
        to: '/work',
    },
    {
        alt: 'A commit graph rising behind the pointer',
        body: 'Got a product idea? We turn it into something people pay for, with the boring parts done properly from day one: <mark>billing, auth, deploys</mark> and <mark>real-time</mark>.',
        cta: 'Talk to us',
        figure: 'branches',
        label: 'Expertise',
        title: 'SaaS products',
        to: '/contact',
    },
    {
        alt: 'A router whose antennas lean toward the pointer',
        body: 'Your data is the crown jewel. We sort out <mark>AWS, Docker, CI/CD</mark> and <mark>monitoring</mark> so your systems stop living on a Jenga tower.',
        cta: 'Talk to us',
        figure: 'router',
        label: 'Expertise',
        title: 'Cloud',
        to: '/contact',
    },
    {
        alt: 'A terminal whose history scrolls under the pointer',
        body: 'Hiring, levelling up a team, or deciding what to do with the old codebase. <mark>Honest assessments</mark> and <mark>clear next steps</mark>, no slide decks.',
        cta: 'Talk to us',
        figure: 'terminal',
        label: 'Expertise',
        title: 'Consultancy',
        to: '/contact',
    },
];
